FROM python:3.11-alpine
RUN apk add --no-cache docker-cli
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY entrypoint.sh .
COPY node_agent.py .
COPY agent_src/ agent_src/
RUN chmod +x entrypoint.sh
CMD ["sh", "entrypoint.sh"]
